# fly.toml app configuration file generated for darwins-cloud on 2025-04-26T22:38:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'darwins-cloud'
primary_region = 'bos'

[build]
[build.args]
GO_VERSION = '1.22.3'

[env]
PORT = '8080'
GIN_MODE = 'release'


[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
